# base-image for node on any machine using a template variable
FROM resin/%%RESIN_MACHINE_NAME%%-node:8

# Defines our working directory in container
WORKDIR /usr/src/node-red

# Install node-red using npm
RUN npm install -g --unsafe-perm node-red

# 
CMD node-red